/* 
 * This file is part of the PooterBot project.
 * 
 * (c) 2018 Daniele Ambrosino <mail@danieleambrosino.it>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file distributed with this source code.
 */
/**
 * Author:  Daniele Ambrosino
 * Created: 25-ott-2018
 */

DROP TABLE IF EXISTS Cities;
DROP TABLE IF EXISTS FemaleNames;
DROP TABLE IF EXISTS Jokes;
DROP TABLE IF EXISTS Judgements;
DROP TABLE IF EXISTS Offenses;
DROP TABLE IF EXISTS Opinions;
DROP TABLE IF EXISTS PhotoComments;
DROP TABLE IF EXISTS PhotoResources;
DROP TABLE IF EXISTS Proverbs;
DROP TABLE IF EXISTS Songs;
DROP TABLE IF EXISTS Speeches;

CREATE TABLE IF NOT EXISTS PhotoResources (
  id     VARCHAR(32) PRIMARY KEY,
  fileId VARCHAR(128) NOT NULL REFERENCES Files (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS Speeches (
  id     VARCHAR(32) PRIMARY KEY,
  fileId VARCHAR(128) NOT NULL REFERENCES Files (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS Songs (
  id     VARCHAR(32) PRIMARY KEY,
  fileId VARCHAR(128) NOT NULL REFERENCES Files (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS Cities (
  id INTEGER UNSIGNED PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Jokes (
  id     TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `text` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Proverbs (
  id     TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `text` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Opinions (
  id     TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `text` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Judgements (
  id     TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `text` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PhotoComments (
  id     TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `text` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Offenses (
  id SERIAL PRIMARY KEY,
  `text` TEXT NOT NULL,
  `self` BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX Offenses_self_idx ON Offenses (`self`);

CREATE TABLE IF NOT EXISTS FemaleNames (
  `name` VARCHAR(12) PRIMARY KEY,
  FULLTEXT FemaleNames_name_idx (name)
)
  ENGINE = InnoDB;
